### ISSUE TITLE
Condee not parsing strings

### ISSUE THREAD

**Issue by khiemlam** [tel/condee#1]
The following parameters are failing with the error messages, "fail: parse error":
"'hi'=='hi'"
'hi'=='hi'
"hi"=="hi"

**Comment by tel** [comment]
Definitely messed up the spec—I had it using double-quoted strings. Should be fixed now. The tests reflect single-quoted strings and I have

```
(condee)> ~/rh/proj/gsk/condee ./dist_condee/build/condee/condee "'ab'=='ab'"                 
bool true
```
